### ISSUE TITLE
Fix `pip install` command

### ISSUE THREAD

**Issue by Piirtola** [venikx/nordea-finnair-transactions#1]
Hi, thanks for sharing your code I was just looking for something like this to use with `hledger`, so you probably saved me some time! I didn't have the motivation to fork this yet, so can't add a PR. But in your `readme.md` the `pip install -t...` is not right `t` flag is used as described below

From: https://stackoverflow.com/questions/48503593/what-is-the-t-flag-for-pip

> -t, --target <dir>
>      Install packages into <dir>.
>      By default this will not replace existing files/folders in <dir>.
>      Use --upgrade to replace existing packages in <dir> with new versions.

You should instead use `r` flag, i.e., `pip install -r requirements.txt`

@venikx

**Comment by venikx** [comment]
Hei @Piirtola, thank you for this. I’m not too familiar yet with writing Python code, nor it’s ecosystem. 

I’m updating the docs as requested.

The parser also has only been used on my own invoices atm (which is about 2-3 of them, so I’m most likely missing some edge-cases with the parsing). I’ve added a summary that you’ll need to verify if it’s the same as the invoice you are paying. If not, you can send an issue with the line where it goes wrong, or send a PR. I’m definitely open to improve this, as I personally use it for my finance, but I’m a Javascript dev and this was my first Python project😅
